### ISSUE TITLE
Downloading .txt (Dynon) does not save first group name

### ISSUE THREAD

**Issue by jmilljr24** [rdamazio/efis-editor#14]
When a name is give for the first group, no name is added to the .txt file. Subsequent group names are applied. When re-uploading the same file, the first group defaults to the name "MAIN GROUP"

Original
![Screenshot from 2024-05-13 16-14-19](https://github.com/rdamazio/efis-editor/assets/16829344/2fd805f9-cd11-4bcc-aa5b-09f8cd043cb0)

Re-Upload
![Screenshot from 2024-05-13 16-15-10](https://github.com/rdamazio/efis-editor/assets/16829344/4f7dd1e6-ee3f-4309-b653-aacef082b7e5)

Test file download
[test1.txt](https://github.com/rdamazio/efis-editor/files/15299481/test1.txt)

**Comment by rdamazio** [comment]
Thanks for the report!

I did that on purpose, but I'm totally open to changing it (or making it an option): my rationale was that, since groups are not supported on Dynon/GRT/AFS, that most people would want their "normal" checklists to have only the checklist title, without a group name (for one, because of the limited columns available to display it).

Do you think it'd be useful to keep the first group name?

(I don't have a Dynon system to test with and get a feel for what makes sense, so really appreciate the feedback - keep it coming)

**Comment by jmilljr24** [comment]
That makes sense. I do have Dynon but have not tested on it yet. I was playing with this site to see how things were implemented.

 I'll close the issue and if there is anything specific with Dynon causing trouble I'll open a new one. Also if you would like me to test any other files with Dynon just let me know. Happy to help.
